### ISSUE TITLE
Removing an object form a resource does not remove the object

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#13]
example:

`causes.remove(some-id)`

does trigger all the remove events correctly, so I can remove the cause from the UI. But when I fetch the causes again from the backend, they are all there again.

**Comment by satyavh** [comment]
btw, I don't think we should enable this from the front-end. We should make some kind of call where we pass `currentUser` and the `objectId`, so that the backend can check if that user is allowed to remove that object.

**Comment by perissology** [comment]
I believe this is fixed
