### ISSUE TITLE
Prevent duplicate request/event processing

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#134]
We don't prevent processing single request/event multiple times. Therefor, there will be duplicate entities or inconsistent data in mongo DB if user or blockchain send feather the same request or event multiple times.

Uniqueness should be implemented in processing requests and events. It should prevent processening the same event or adding the same entity to db multiple times.

**Comment by aminlatifi** [comment]
This feather may solve https://github.com/Giveth/giveth-dapp/issues/1005

**Comment by arbreton** [comment]
Test on develop passed, testing on beta now

**Comment by aminlatifi** [comment]
@arbreton is there any reason for reopening this?
