### ISSUE TITLE
Find conflicts on feathers and smart contract

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#146]
We should evaluate state on smart contract and feathers servers. If these two are not consistent, one of them would have bug (or both)

**Comment by aminlatifi** [comment]
First step was finding conflicts on milestones and campaigns. The result on beta is [conflict_result.txt](https://github.com/Giveth/feathers-giveth/files/4035222/conflict_result.txt)

**Comment by aminlatifi** [comment]
> First step was finding conflicts on milestones and campaigns. The result on beta is [conflict_result.txt](https://github.com/Giveth/feathers-giveth/files/4035222/conflict_result.txt)

It found 818 conflicts!

**Comment by aminlatifi** [comment]
@GriffGreen Cancel campaign scenario does not match in feathers and smart contract. By feathers logic, if a campaign is canceled all of its milestones should be canceled too. However we have a case in network that campaign (id 12) is canceled, but its milestone (id 35) is not!
```
➜  utils git:(f_conflict_resolver) ✗ node ./getPledgeAdmin.js 35
{ type: 'Project',
  addr: '0xf2272CB5ca1997A3c0fb85EDf93B55825246B3aD',
  name: 'DAppLion: June 25th - July 1st',
  url: '',
  commitTime: '0',
  parentProject: '12',
  canceled: false,
  plugin: '0xf2272CB5ca1997A3c0fb85EDf93B55825246B3aD' }
➜  utils git:(f_conflict_resolver) ✗ node ./getPledgeAdmin.js 12  
{ type: 'Project',
  addr: '0x13d7ca67e4b75684096a7544e1544C07DFD497e3',
  name: 'DAppNode',
  url: '',
  commitTime: '0',
  parentProject: '0',
  canceled: true,
  plugin: '0x13d7ca67e4b75684096a7544e1544C07DFD497e3' }
➜  utils git:(f_conflict_resolver) ✗ 
```
This problem came up when we have a money transfer to a milestone pledge after the parent campaign is canceled. Is this donation valid or it should be ignored (feathers ignored)?

**Comment by aminlatifi** [comment]
@GriffGreen Is it true that if a milestone is canceled its all money should be reverted? 
If yes, we have an weird milestone which is canceled, but there is money in its pledge!
The milestone is https://beta.giveth.io/campaigns/5d9466be0be6c23fee64fbda/milestones/5d486d5be2b294308843fd4f
The milestone project id in smart contract is 1667
```
{ type: 'Project',
  addr: '0x494941AF6cC8a7Ff9208Dd11F2A87f20f44262Ca',
  name: 'Jeff\'s Europe Conference & Tech Expenses',
  url: '/ipfs/QmdbXw9rCzpwMmjj64p8nZmK3gue9NE82PxABeHsPA2Qaq',
  commitTime: '0',
  parentProject: '1402',
  canceled: true,
  plugin: '0x494941AF6cC8a7Ff9208Dd11F2A87f20f44262Ca' }
```
And the pledge number is 5276
```
{ delegates: [],
  amount: '44200000000000000000',
  owner: '1667',
  token: '0xB5aFaeD1AE9B0485a859023e1372C100b11E98ab',
  intendedProject: '0',
  commmitTime: '0',
  oldPledge: '4587',
  pledgeState: 'Pledged' }
```

**Comment by aminlatifi** [comment]
We have duplicate pledgeAdmin entity in smart contract for a single user! For instance pledgeAdmin ids 1217 and 1249 referring to one user.
```
➜  utils git:(f_conflict_resolver) ✗ node ./getPledgeAdmin.js 1217                              
{ type: 'Giver',
  addr: '0x6CFFfBe3dD2539085BeCB326dEe2012b0eD5bEB1',
  name: '',
  url: '',
  commitTime: '259200',
  plugin: '0x0000000000000000000000000000000000000000' }
➜  utils git:(f_conflict_resolver) ✗ node ./getPledgeAdmin.js 1249
{ type: 'Giver',
  addr: '0x6CFFfBe3dD2539085BeCB326dEe2012b0eD5bEB1',
  name: '',
  url: '',
  commitTime: '259200',
  plugin: '0x0000000000000000000000000000000000000000' }
```
And this user has donated two time to [this campaign](https://beta.giveth.io/campaigns/5c0e84ea06392d786b64d484), but one of them is saved in feathers.

**Comment by GriffGreen** [comment]
Shit. Yes that is a big problem :-( the milestones, when canceled are supposed to revert the pledges they have to their old pledge :-( 

I hope that the funds in kris' milestone arent stuck as well: https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5df00afa71e84069aad0a228

**Comment by aminlatifi** [comment]
Another weird condition
This [campaign](https://beta.giveth.io/campaigns/5bd7ad6cdb72b92a41002fc5) with id 414 is canceled after this event:
```
  {
    "blockNumber": 3674783,
    "transactionHash": "0x36a4a4d81482824c99ae291b0d802fc33ba9148bc4f142a5435eee74ae2408e5",
    "transactionIndex": 8,
    "blockHash": "0xf97fc77d1ad384f6023201b078783ee182fed3d30364282b695c1e0bf388f239",
    "logIndex": 8,
    "removed": false,
    "returnValues": {
      "0": "414",
      "idProject": "414"
    },
    "event": "CancelProject",    
  }
```
Though its [child milestone](https://beta.giveth.io/campaigns/5d110631994eac53adc8f21e/milestones/5bd8f88ddb72b92a41002ffe) with id 424 is not canceled in smart contract:
```
➜  utils git:(f_conflict_resolver) ✗ node ./getPledgeAdmin.js 414
{ type: 'Project',
  addr: '0xa612D24d79d7d8305425339d0Dc990c04cAE06bf',
  name: 'Yearly costs for GRACEaid shop, warehouse and van',
  url: '',
  commitTime: '0',
  parentProject: '0',
  canceled: true,
  plugin: '0xa612D24d79d7d8305425339d0Dc990c04cAE06bf' }
➜  utils git:(f_conflict_resolver) ✗ node ./getPledgeAdmin.js 424
{ type: 'Project',
  addr: '0xEe16E5647482ffc8d7D6cD165a844C17C8D9f447',
  name: 'GRACIE van yearly costs',
  url: '',
  commitTime: '0',
  parentProject: '414',
  canceled: false,
  plugin: '0xEe16E5647482ffc8d7D6cD165a844C17C8D9f447' }
```
Also milestone has a pledge with id 1118 and it money moved several blocks after campaign is canceled by another transaction
```
  {
    "blockNumber": 3949366,
    "transactionHash": "0x8c719c5d6b3b1d8b277971c2795debdb65d7946ccfc4916ad43743a9345d5f64",
    "transactionIndex": 7,
    "blockHash": "0xa4dc51c950543430377bd5f6143cdc25a6fefa62f340555ed997f8c815b06dd8",
    "logIndex": 11,
    "removed": false,
    "returnValues": {
      "0": "1118",
      "1": "875",
      "2": "1000000000000000000",
      "from": "1118",
      "to": "875",
      "amount": "1000000000000000000"
    },
    "event": "Transfer",    
  }
```
The milestone has canceled in feathers.

**Comment by aminlatifi** [comment]
These are instances showing bug in smart contract. The amount is the value in smart contract and amount remaining is the expected value obtained from simulation.

1. The owner of pledge 9 is admin 12. The owner is canceled, but money in pledge is not reverted!
```
Pledge 4 amount 157238775699227929 does not equal total amount remaining 207238775699227929
Pledge 9 amount 50000000000000000 does not equal total amount remaining 0
```
2. The owner of pledge 912 is admin 414. The owner is canceled, but money in pledge is not reverted!
The owner of pledge 913 is admin 414. The owner is canceled, but money in pledge is not reverted!
```
Pledge 911 amount 0 does not equal total amount remaining 400000000000000000
Pledge 912 amount 200000000000000000 does not equal total amount remaining 0
Pledge 913 amount 200000000000000000 does not equal total amount remaining 0
```
3. The owner of pledge 928 is admin 360. The owner is canceled, but money in pledge is not reverted!
```
Pledge 927 amount 0 does not equal total amount remaining 10000000000000000
Pledge 928 amount 10000000000000000 does not equal total amount remaining 0
```
4. The owner of pledge 1082 is admin 455. Admin 455 is canceled, but money in pledge is not reverted!
```
Pledge 1081 amount 0 does not equal total amount remaining 1000000000000000000
Pledge 1082 amount 1000000000000000000 does not equal total amount remaining 0
```
5. The owner of pledge 1178 is admin 418. The owner is canceled, but money in pledge is not reverted!
```
Pledge 1177 amount 0 does not equal total amount remaining 510000000000000000
Pledge 1178 amount 510000000000000000 does not equal total amount remaining 0
```
6. The owner of pledge 3296 is admin 996. The owner is canceled, but money in pledge is not reverted!
```
Pledge 1851 amount 170283456055238132458 does not equal total amount remaining 470283456055238132458
Pledge 3256 amount 300000000000000000000 does not equal total amount remaining 0
```
7. The owner of pledge 2368 is admin 916. The admin 916 owner is admin 910 and it's canceled. But the money in the pledge is not reverted!
```
Pledge 2366 amount 0 does not equal total amount remaining 10000000000000000000
Pledge 2368 amount 10000000000000000000 does not equal total amount remaining 0
```
8. The owner of pledge 3387 is admin 1066. The owner is canceled, but money in pledge is not reverted!
```
Pledge 3370 amount 2000000000000000000 does not equal total amount remaining 3000000000000000000
Pledge 3387 amount 1000000000000000000 does not equal total amount remaining 0
```
9.  Admins 1707 and 1762 are canceled, but their pledges are not reverted!
```
Pledge 3888 amount 0 does not equal total amount remaining 1042606600000000000
Pledge 6123 amount 42606600000000000 does not equal total amount remaining 0
Pledge 6157 amount 1000000000000000000 does not equal total amount remaining 0
```
10. The owner of pledge 4895 is admin 1427. The owner is canceled, but money in pledge is not reverted!
```
Pledge 4363 amount 0 does not equal total amount remaining 50000000000000000000
Pledge 4895 amount 50000000000000000000 does not equal total amount remaining 0
```
And several other similar conflicts in smart contract can be found in attached log file.
[log.txt](https://github.com/Giveth/feathers-giveth/files/4218995/log.txt)

**Comment by aminlatifi** [comment]
Initial version of syncing script ran on beta data...
The result of log can be find in the file
[findConflictLog.txt.zip](https://github.com/Giveth/feathers-giveth/files/4225171/findConflictLog.txt.zip)

**Comment by aminlatifi** [comment]
> Initial version of syncing script ran on beta data...
> The result of log can be find in the file
> [findConflictLog.txt.zip](https://github.com/Giveth/feathers-giveth/files/4225171/findConflictLog.txt.zip)

By running this script, pledged donations (Paying and Paid are excluded) are created with total value of 4178.268493245418056727 tokens (eth/sai/dai)
And 2627.413206884681651734 tokens (eth/sai/dai) are returned to the cycle

**Comment by GriffGreen** [comment]
Worth checking and confirming that this bug didnt happen in https://beta.giveth.io/campaigns/5cfe3366228b71296a491fa7/milestones/5d1ba874bd45530e23ad86ed

**Comment by aminlatifi** [comment]
[ownerCanceledButNotReverted.txt](https://github.com/Giveth/feathers-giveth/files/4240740/ownerCanceledButNotReverted.txt) is the list of pledges whose owner is canceled, but their money is not reverted!
[successfulRevert.txt](https://github.com/Giveth/feathers-giveth/files/4240741/successfulRevert.txt) is the list of pledges whose owner is canceled and their money is reverted as expected.

> Hint: `isCanceled` value is canceled status obtained by simulation, and `canceled` is the value in the pledge admin in smart contract

**Comment by aminlatifi** [comment]
> [ownerCanceledButNotReverted.txt](https://github.com/Giveth/feathers-giveth/files/4240740/ownerCanceledButNotReverted.txt) is the list of pledges whose owner is canceled, but their money is not reverted!
> [successfulRevert.txt](https://github.com/Giveth/feathers-giveth/files/4240741/successfulRevert.txt) is the list of pledges whose owner is canceled and their money is reverted as expected.
> 
> > Hint: `isCanceled` value is canceled status obtained by simulation, and `canceled` is the value in the pledge admin in smart contract

By investigating all canceled project cases I found that for each successfully reverted money from a canceled projects there is a corresponding `Transfer` event to revert money.
This means in smart contract if a project is canceled for each of its non empty pledges a `Transfer` event should be emitted.
For each canceled project with non empty pledge these events has not emitted!

**Comment by GriffGreen** [comment]
Not easy to use by anyone besides Amin... It could use a how to video ... either way... this is done!!
