### ISSUE TITLE
Keep track of total amount raised for DACs/Campaigns

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#15]
When delegating money away from DACs/Causes, the donations will currently disappear from that DAC/Cause. That means we cannot show the total amount raised for that DAC/Campaign.

So in case all money has been delegated, the total amount raised will show 0

That is not a very good incentive for new donors. Plus it will show the DAC/Campaign has no community

**Comment by zdenekkuncar** [comment]
The donations should most likely stay displayed there in appropriate status.

In a campaign, we should display the amount of money delegated to all of its milestones.

In a DAC, it should be all the delegations made. Imho, without them it doesn't make much sense.

**Comment by perissology** [comment]
in the develop branch, there is currently a `totalDonated` and `donationsCount` property for a dac, campaign, & milestone.

however, this does need to be updated with additional logic to handle delegations, cancelations, etc.

**Comment by satyavh** [comment]
`totalDonated` comes through as a very long string, not very usable in the UI. Example:
`0200000000000000000002000000000000000000`

**Comment by satyavh** [comment]
These counters do not update for a Milestone after money has been committed.

**Comment by satyavh** [comment]
I also need `maxAmount` added to the milestone service

**Comment by satyavh** [comment]
I noticed that these counters are not included when they are 0
Reproduce: create a new DAC. Then the counters are not returned from the service.
For now I hacked around it in the UI, but the correct way is to always return the counters.

**Comment by perissology** [comment]
I added the counters when we create the dac/campaign/milestone, but hadn't pushed them yet. They are there now.

Regarding `maxAmount` this is already there.

**Comment by perissology** [comment]
okay, this has been updated. These counters will be updated on on incoming donations (only committed donations for campaigns & milestones)
