### ISSUE TITLE
Need a way to get wallet balance

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#16]
We should fetch the wallet balance before the donation popup is shown, so we can make sure the donator does not donate more than is in the wallet.

**Comment by perissology** [comment]
this is done in web3 branch

**Comment by satyavh** [comment]
ok wasn't aware of that branch. When will you merge?

**Comment by perissology** [comment]
now in develop branch. `GivethWallet.getBalance()`.

Also need to factor gas into this.
