### ISSUE TITLE
DAC Creation can not be confirmed on Mac OS

### ISSUE THREAD

**Issue by Troublor** [Giveth/feathers-giveth#161]
Transactions can not be confirmed on Mac OS
<img width="951" alt="Screenshot 2020-03-05 at 23 48 44" src="https://user-images.githubusercontent.com/14846504/75998461-db967000-5f3b-11ea-911a-d8b428dae096.png">
All transaction is just pending forever. 
I'm using feathers-giveth on local machine. (Mac)
There isn't much information in the console log: 
```
yarn run v1.22.0
$ babel-watch -p transform-object-rest-spread ./src/index.js
info: Using feathers mongo url mongodb://localhost:27017/giveth 
info: starting blockchain watchers
info: Feathers application started on localhost:3030
info: Using DappMailer url http://127.0.0.1:3050
error: Error attempting to connect to ipfsApi. We will not be able to manage file pinningconnect ECONNREFUSED 127.0.0.1:5001 Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14) 
info: Connected to Mongo
info: error: authentication - Method: create - Challenge = 2GgW4SprMv2txitTjKkT
```

**Comment by aminlatifi** [comment]
You should run local ipfs and ethereum networks.

**Comment by Troublor** [comment]
Isn't ipfs optional according to the README.md? Local ethereum network is running using `yarn start:networks`. I used Linux machine before and it works all fine, but not on Mac.

**Comment by aminlatifi** [comment]
Unintended changes to default config is reverted.
@Troublor Thanks for reporting. It wasn't working on any platform with default config and now fixed.
