### ISSUE TITLE
Change the URL's to use Project ID's instead of some random hash

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/feathers-giveth#184]
From: https://beta.giveth.io/campaigns/5c0f381f06392d786b64d4dd/milestones/5cd9c5a3e4ee5d18e7bad871

To:
https://beta.giveth.io/campaigns/102/milestones/1236

**Comment by aminlatifi** [comment]
I think campaignId should not exists in a milestone URL. Current URL of milestones includes campaignId, but it's useless.

**Comment by aminlatifi** [comment]
@GriffGreen The proposed milestones doesn't have `Project ID` field 🤔

**Comment by GriffGreen** [comment]
It would be nice to have the name of the milestone in the link too....

**Comment by aminlatifi** [comment]
@mahdine
- [ ] Let's create project slug for any accepted project (not in proposed or rejected state)
- [ ] Use that slug in front-end and redirect previous format of links to new ones

**Comment by mdehghani** [comment]
@aminlatifi Do you mean to use slug in Milestones only? Is it necessary to add slug for campaigns too?

**Comment by aminlatifi** [comment]
> @aminlatifi Do you mean to use slug in Milestones only? Is it necessary to add slug for campaigns too?

Yes, for all kind of projects we will use slug (DAC, Campaign and Milestone)
