### ISSUE TITLE
Improve typography and grid for readability

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#22]
Actually @alanborger is going to do this, but I need to implement the css

**Comment by alanborger** [comment]
Hi @satyavh , can you send me some screenshots of both the grid / typography issue and the profile page layout..? I can work on top of that and send you back a few suggestions, how does that sound..?

**Comment by satyavh** [comment]
Hey, I slacked you all the info

**Comment by satyavh** [comment]
Issue moved to [Giveth/giveth-dapp #33](https://github.com/Giveth/giveth-dapp/issues/33) via [**ZenHub**](https://www.zenhub.com/)
