### ISSUE TITLE
Remove pendingAmountRemaining from donations in simulation script

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#244]
Donation entity has a temporary field `pendingAmountRemaining` which is filled when donation is in pending state and should be removed when the status of donation is achieved.

Imperfect donation process doesn't remove `pendingAmountRemaining` from donations and simulation script doesn't remove this field too. Simulation script should be updated to address this problem and remove the field

**Comment by aminlatifi** [comment]
@mohammadranjbarz Is it fixed by new patches to simulation script?
?

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
Yest it's ok now, you can see my test cases results in this issue comments: https://github.com/Giveth/giveth-1-simulation/issues/3

**Comment by aminlatifi** [comment]
> @aminlatifi
> Yest it's ok now, you can see my test cases results in this issue comments: [Giveth/giveth-1-simulation#3](https://github.com/Giveth/giveth-1-simulation/issues/3)

@mohammadranjbarz Thanks
