### ISSUE TITLE
Milestone paid email shows incorrect value of amount

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#246]
This email is sent after receiver collected 400 DAI, but the email content says 0 DAI
![image](https://user-images.githubusercontent.com/5684607/97555287-301bbd80-19ed-11eb-9a04-a94d4b432ef5.png)

**Comment by mohammadranjbar** [comment]
@mahdine 

It would be great if we can fix it with pair programming

**Comment by mahdine** [comment]
I welcome @mohammadranjbar. How can I help?

**Comment by mohammadranjbar** [comment]
@mahdine 

I think with data that we persist on db this is impossible to calculate correct amount,
I want a  time to work pair together to make sure it's possible or not, It maybe helpful for my onboarding as well

**Comment by aminlatifi** [comment]
I assigned @mdehghani to help, not @mahdine

**Comment by aminlatifi** [comment]
https://develop.giveth.io/campaigns/5d2eb691e31bd24ef8bd3fa8/milestones/5ec296472f62f84493a277e4 is a sample of payment conversation, which is created once and updated later

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I can't understand , do you say the last conversation amount is different from what we send to email?
(I dont know that you are aware or not the email just send to milestone owner when the milestone is fully funded not after every payment collection so maybe the  `totalDonated` value works fine for emails)

![image](https://user-images.githubusercontent.com/9850545/99898342-f2d9e100-2cb5-11eb-92f9-06f4209462a5.png)

**Comment by aminlatifi** [comment]
> I can

The last conversation has correct value, but after processing all events related to the payment. A payment transaction can produce multiple transfer events, we process those and create/update the payment conversation. We can rely on last payment conversation value after being sure we have processed all related events. In other word we should send email after processing last event

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
It's not up to us, when user wants to collect we should send him email,
I'v an idea :
The sum of all conversation's amounts is equal to `totalDonated`, so the  `totalDonated` minus all conversations except the last one should return the amount of last collected

**Comment by aminlatifi** [comment]
> @aminlatifi
> It's not up to us, when user wants to collect we should send him email,
> I'v an idea :
> The sum of all conversation's amounts is equal to `totalDonated`, so the `totalDonated` minus all conversations except the last one should return the amount of last collected

Good idea 👏

Use transaction hash to distinct other conversations, and notice we should send email once!
An important point is that we send `Milestone paid` email when milestone status is changed (milestone hook), but we should do it somewhere in donation hooks.

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
Now when user wants to collect or disburse the status changes from `paying` to `paid` and we send email to milestone's recipient,
But now we want after donations meet the milestone maxAmount send email, before user's action?

**Comment by aminlatifi** [comment]
> @aminlatifi
> Now when user wants to collect or disburse the status changes from `paying` to `paid` and we send email to milestone's recipient,
> But now we want after donations meet the milestone maxAmount send email, before user's action?

No, we should put the logic at the same place we create payment conversation. Current implementation is wrong, because not all milestone will have `paying` or `paid` status. Also, a milestone can be collected/disbursed multiple times (and still be in `InProgress` state) and we should send email for each

**Comment by mohammadranjbarz** [comment]
> > @aminlatifi
> > Now when user wants to collect or disburse the status changes from `paying` to `paid` and we send email to milestone's recipient,
> > But now we want after donations meet the milestone maxAmount send email, before user's action?
> 
> No, we should put the logic at the same place we create payment conversation. Current implementation is wrong, because not all milestone will have `paying` or `paid` status. Also, a milestone can be collected/disbursed multiple times (and still be in `InProgress` state) and we should send email for each

https://github.com/Giveth/feathers-giveth/pull/276

**Comment by aminlatifi** [comment]
@horus2021 Please test it.

**Comment by mohammadranjbarz** [comment]
related to #276

**Comment by horus2021** [comment]
Ok, I began testing ;)

**Comment by GriffGreen** [comment]
Maybe affected by the backend upgrade?

**Comment by mohammadranjbarz** [comment]
> Ok, I began testing ;)
> 
> ![image](https://user-images.githubusercontent.com/65175075/101979828-ab6fc080-3c75-11eb-9798-4ff1440b968a.png)
> 
> I have donated 0.001 xDAI on Dec 12 and I can see my donations as _commited_ in giveth.io but not in ether scan?
> 
> https://rinkeby.etherscan.io/address/0x6b81e289f1f0db53e56D7F8C29E6c2d6645A1Bd7
> 
> If long delay in Rinkeby network why committed???!!!!!
> 
> I also did not get any notification email.

Did you collect your donations?
because your donations have commited status,
after you collect your donations the money should go to milestones's recipient addresss, and the donation status would change to `Paid`

@horus2021

**Comment by horus2021** [comment]
@mohammadranjbarz  as far as I know, when I donate money goes to Giveth smart contract. This is called committed status. I should see this transaction in network. When I collect, money goes from Giveth to my wallet. This is called paid. I should see another transaction for this in network again. @aminlatifi  pleas correct me if I misunderstood.

**Comment by aminlatifi** [comment]
@horus2021 On donation two transactions are created, one on home network (mainnet in beta) and on in foreign network (rinkeby). On old donation list component which still is used on milestone view you can see the former one (home tx)(it's the ref of donation status link). 
When you collect/disburse three transactions are needed to you have crypto in you wallet. The first is on foreign network and sends crypto to foreign bridge (happens immediately), the second one one is done few moment after on home network (is done by bridge process), and the third tx is after security guard approve this payment which is few days later.

**Comment by horus2021** [comment]
Seemingly notification email still not working.
Let me write down test steps.

Horus (I) donates 0.001 xDAI to promote Plato philosophy. The giveth confirms the Tnx. See below confirmation.
in Horus donation list

![image](https://user-images.githubusercontent.com/65175075/103178140-682c6900-4895-11eb-9f6e-3698c5ad49fb.png)

in Leader board
![image](https://user-images.githubusercontent.com/65175075/103178157-9b6ef800-4895-11eb-8964-c1b7934ec4a5.png)

in ropsten.etherscan.io
![image](https://user-images.githubusercontent.com/65175075/103178172-b7729980-4895-11eb-9638-6a5d8d300cee.png)

I expect giveth drops an emial on khanih@gmail.com, but nothing after 0.5 hours.

**Comment by mohammadranjbarz** [comment]
> Hey @mohammadranjbarz Seemingly notification email still not working.
> Let me write down test steps.
> 
> Horus (I) donates 0.001 xDAI to promote Plato philosophy. The giveth confirms the Tnx. See below confirmation.
> in Horus donation list
> 
> ![image](https://user-images.githubusercontent.com/65175075/103178140-682c6900-4895-11eb-9f6e-3698c5ad49fb.png)
> 
> in Leader board
> ![image](https://user-images.githubusercontent.com/65175075/103178157-9b6ef800-4895-11eb-8964-c1b7934ec4a5.png)
> 
> in ropsten.etherscan.io
> ![image](https://user-images.githubusercontent.com/65175075/103178172-b7729980-4895-11eb-9638-6a5d8d300cee.png)
> 
> I expect giveth drops an emial on [khanih@gmail.com](mailto:khanih@gmail.com), but nothing after 0.5 hours.

I think we have some misunderstanding here, did you collect the donations?
because this issue is for sending email after collecting money, not donating money,
I would appreciate if this time that you want to test we check it together, maybe it helps to test and troubleshoot more faster than now

**Comment by horus2021** [comment]
Horus collected money from [quad test](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201/milestones/5f351630b6f1f80a310f2090). Horus did not get email and status did not change form commited to paid. I guess delay is due to heavy traffic in Rinkeby.

- [ ] @horus2021  Check it on 31 Dec

**Comment by horus2021** [comment]
Complex Test Case suggested by @mohammadranjbarz 

1. Donate 0.001 xDai
2. Donate 0.002 xDai
3. Donate 0.00002 Eth
4. Donate 0.00002 Eth

Collect Money.
Expectation
1. See a comment for collect event.
2. Get and email notification for collect 0.003 xDai  + 0.00004 Eth

**Comment by horus2021** [comment]
@aminlatifi  horus (as owner ) marks [uncapped mmmm milestone](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201/milestones/5fc51376a00c0951e4db7ace). complete. Now sunny (as reviewer) wants to approve this, but sunny does not see anything to do this. Please help. :(

**Comment by horus2021** [comment]
@mohammadranjbarz  issue has been fixed. Thanks a million.

**Comment by horus2021** [comment]
@aminlatifi close this issue please.
