### ISSUE TITLE
rename all instances of `cause` to `dac`

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#26]
@perissology commented on [Tue Sep 26 2017](https://github.com/Giveth/giveth-dapp/issues/19)

to keep things consistent

---

@satyavh commented on [Fri Sep 29 2017](https://github.com/Giveth/giveth-dapp/issues/19#issuecomment-333146899)

This has been done on the React side, I'm copying this story over the Feathers repro, because we still need to rename the `/causes` service to `/dacs`

**Comment by perissology** [comment]
already done

**Comment by perissology** [comment]
in develop branch
