### ISSUE TITLE
Add husky for run tests end eslint before push

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/feathers-giveth#278]
@aminlatifi 
If you are ok I add some hooks(with husky) to `git push` and `git commit` to cant commit if eslint emit errors and cant push if tests doesnt passed, it makes fewer failed jobs in `CI/CD` pipeline

**Comment by aminlatifi** [comment]
Good idea, add husky please. Please add just for `push` action.

**Comment by mohammadranjbarz** [comment]
@aminlatifi  
Ok I'll do it

**Comment by aminlatifi** [comment]
> @aminlatifi
> Ok I'll do it
Sorry, I changed my opinion... circleci do it for us

**Comment by aminlatifi** [comment]
Just add something fast like lint error checking

**Comment by mohammadranjbarz** [comment]
> Just add something fast like lint error checking 

Ok, it seems good
