### ISSUE TITLE
When delegating from campaign to a milestone, the money is instantly locked in the milestone

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#28]
reproduce:

1. make donation to a campaign that has InProgress milestones
2. go to my delegations, delegate to a milestone
3. go to my donations, the money will be committed

Expected:
3. I expect the commit and reject button to show up (`status: to_approve`).
I also expect `proposedProject` to be set so it will show a nice 'delegated' label.

**Comment by perissology** [comment]
that is the expected behavior. A campaign has control of the funds, so the donor no longer does. The only "delegates" in the system are dacs.
