### ISSUE TITLE
rateEqSymbol doesn't work 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#280]
On develop we have test tokens and their symbol doesn't get any rate from api. We used rateEqSymbol and it revealed a bug!
Currently every rate for `XDAI` token resolves to 0 on develop while its rateEqSymbol is set to `DAI`

**Comment by horus2021** [comment]
It works!

**Comment by horus2021** [comment]
@papermache . This should be close, but I do not have permission in feather. Please close.
