### ISSUE TITLE
Upgrade mongoose and feathers

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#289]
Mongoose and Feathers are the core of feathers-giveth, both are outdated. Upgrading them is necessary to upgrade node version.
Refs Giveth/giveth-dapp#1576

**Comment by GriffGreen** [comment]
blocking the switch to node 10

**Comment by mohammadranjbarz** [comment]
https://github.com/Giveth/feathers-giveth/pull/295#issuecomment-744293641

**Comment by mohammadranjbarz** [comment]
> blocking the switch to node 10

In develop server we already updated node version to `10` and I think it's not a blocker for updating to node `10`

**Comment by aminlatifi** [comment]
@mohammadranjbarz Can we upgrade just mongo driver without touching mongoose?

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I didn't test already, but I'll do it 
PS: I read mongodb email that you sent to me

**Comment by aminlatifi** [comment]
Even though we had added compatible version of mongodb driver to our dependency, mongoose uses version 3.0.8 underneath. Mongoose driver is not compatible with the current mongodb version (4.2).
So we need to upgrade mongoose and other packages which are dependent.

https://docs.mongodb.com/drivers/node/compatibility
