### ISSUE TITLE
No Milestone paid email when the recipient is the campaign

### ISSUE THREAD

**Issue by horus2021** [Giveth/feathers-giveth#315]
[triple test](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201/milestones/5f22b2f69e4f03782453b658) milestone is of [promote Plato philosophy](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201) campaign, the recipient of triple test is promote Plato philosophy campaign. When Horus as the owner of triple test collect money I expect Horus as the owner of campaign gets a milestone paid email. But horus does not get any email.

**Comment by horus2021** [comment]
@GriffGreen, This is related to #246  and I guess @mohammadranjbarz should work on it, but I cannot assign him in feather.

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
@horus2021 
Now when recipient is campaign or anonymous user because we don't have recipient or recipient.email , I send donation collected email to email of milestone's owner

**Comment by aminlatifi** [comment]
@mohammadranjbarz It's the feathers response of get method on milestones
https://feathers.beta.giveth.io/milestones/5f85acfc2cad896ca07b345f

![image](https://user-images.githubusercontent.com/5684607/104843841-ee126180-58e1-11eb-8ab5-61370971ae1e.png)

The campaign seems to be accessible and we can get the campaign owner and his/her email

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
Yes Amin you are right , 
the problem if being recipient is null , is for the milestone that have anonymous users as recipient you can see it in here
https://feathers.beta.giveth.io/milestones/5ff315312d93392e76e6b6db

but not sending was for another issue that fixed in this PR

**Comment by horus2021** [comment]
> 
> 
> @aminlatifi
> @horus2021
> Now when recipient is campaign or anonymous user because we don't have recipient or recipient.email , I send donation collected email to email of milestone's owner
@mohammadranjbarz  When recipient is campaign and campaign owner is not anonymos (has profile with email address), the email should be sent to campaign owner in this case.

**Comment by mohammadranjbarz** [comment]
@horus2021 
Now this is what you want
we should merge it to develop then you can test it

**Comment by horus2021** [comment]
Thank @mohammadranjbarz I am looking forward to test it!

**Comment by aminlatifi** [comment]
We should implement sending email to Campaign Owner, @mohammadranjbarz is it right?

**Comment by mohammadranjbarz** [comment]
> We should implement sending email to Campaign Owner, @mohammadranjbarz is it right?

@aminlatifi 
Now we are sending this email when the user collect the money:
`info: sending email notification to mranjbar.z2993@gmail.com > request-delegation`
isn't enough?

**Comment by GriffGreen** [comment]
Issue needs to be clarified

**Comment by GriffGreen** [comment]
Related to Email overhaul

**Comment by horus2021** [comment]
Thanks @mohammadranjbarz . It works. Excellent Job. When horus (campaign owner) clicks disburse button in campaign he got the below.

![image](https://user-images.githubusercontent.com/65175075/106033342-e7a49680-60e6-11eb-80a4-ff2921bdd777.png)
