### ISSUE TITLE
Conversion rate service problem on resolving old rates from coingecko

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#324]
The implemented rate resolver from coingecko doesn't resolve old rates. It's calls coingecko api using method as below which resolves empty rates at the moment I am writing this issue.
`https://api.coingecko.com/api/v3/coins/panvala-pan/market_chart/range?vs_currency=USD&from=1606784400&to=1606827600`

This problem causes feathers resolve rate 1$ per PAN for that moment.

**Comment by mohammadranjbarz** [comment]
based on documentation, Hourly data will be used for duration between 1 day and 90 day, so I changed  the 12 hours from 24 hours.

https://www.coingecko.com/api/documentations/v3#/coins/get_coins__id__market_chart_range

![image](https://user-images.githubusercontent.com/9850545/103332962-4f80a680-4a81-11eb-9ba3-200e4c35fff5.png)
