### ISSUE TITLE
include _id of the type in /donations/history

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#33]
It is necessary to include the _id of the type that the donation was made to, for querying the right donation. 

Example: 
Fetch all donation/history for DAC with `{ _id: abcd }`

**Comment by perissology** [comment]
this is already included in the same style as the donations...

To find all donations to a dac:
```
query: {
  delegateType: 'dac',
  delegateId: 'feathers_dac_id'
}
```

To find all donations to a campaign:
```
query: {
  ownerType: 'campaign',
  ownerId: 'feathers_campaign_id'
}
```
