### ISSUE TITLE
getting mongo error on develop error: user is not allowed to do action [find] on [giveth-develop.milestones]

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/feathers-giveth#335]
This problem happens in develop server a lot, that maybe related to atlas mongodb

![image](https://user-images.githubusercontent.com/9850545/103437150-33276a00-4c39-11eb-9fc9-fa7802a83a3d.png)

**Comment by mohammadranjbarz** [comment]
I found something that may help, it seems that it's atlas mongo problem

https://stackoverflow.com/a/53948121/4650625

**Comment by aminlatifi** [comment]
Fixed by DB upgrade
