### ISSUE TITLE
Near 2 Days Delay Between Milestone Owner Mark Complete and Milestone Reviewer See (Approve/

### ISSUE THREAD

**Issue by horus2021** [Giveth/feathers-giveth#337]
@aminlatifi  horus (as owner ) marks [uncapped mmmm milestone](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201/milestones/5fc51376a00c0951e4db7ace) at 9pm Jan 1. complete. 

The [transaction](https://rinkeby.etherscan.io/tx/0x9e4c5be492b4e8bed6b3b750512152148cf2063dad446ebe1ec90acea9e82812) registered in Rinkeby blockchain aroung 9 pm Jan 1

Horus Requested Review was displayed 3 pm Ja 3!!
![image](https://user-images.githubusercontent.com/65175075/103486367-93253880-4e12-11eb-83e6-15d73c70c021.png)

Then sunny (as reviewer) saw approve button.

This 2 days delay is normal.

**Comment by GriffGreen** [comment]
This is not expected behavior... it should be instant... I wonder what that was about!

**Comment by GriffGreen** [comment]
We can test it and see whats up!

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/105870911-02570c80-600e-11eb-82ca-ac909ffe4e37.png)
I couldn't reproduce it myself

**Comment by aminlatifi** [comment]
@horus2021 Nice catch
It happened because the event was processes two days later, I fixed it to set tx timestamp as conversation date

**Comment by horus2021** [comment]
@aminlatifi Thanks, but I think the problem is something else. Let me clarify it. The transaction is registere 9 pm Jan 1 at Rinkeby, why it is displayed in develop after two days! As far as I know the main cause of latency is Rinkeby blockchain. When something regitered there it should be updated (reflected)  promptly in develop giveth

> 
> 
> @aminlatifi horus (as owner ) marks [uncapped mmmm milestone](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201/milestones/5fc51376a00c0951e4db7ace) at 9pm Jan 1. complete.
> 
> The [transaction](https://rinkeby.etherscan.io/tx/0x9e4c5be492b4e8bed6b3b750512152148cf2063dad446ebe1ec90acea9e82812) registered in Rinkeby blockchain aroung 9 pm Jan 1
> 
> Horus Requested Review was displayed 3 pm Ja 3!!
> ![image](https://user-images.githubusercontent.com/65175075/103486367-93253880-4e12-11eb-83e6-15d73c70c021.png)
> 
> Then sunny (as reviewer) saw approve button.
> 
> This 2 days delay is normal.

**Comment by aminlatifi** [comment]
> @aminlatifi Thanks, but I think the problem is something else. Let me clarify it. The transaction is registere 9 pm Jan 1 at Rinkeby, why it is displayed in develop after two days! As far as I know the main cause of latency is Rinkeby blockchain. When something regitered there it should be updated (reflected) promptly in develop giveth
> 
> > @aminlatifi horus (as owner ) marks [uncapped mmmm milestone](https://develop.giveth.io/campaigns/5eca6a1c99915a4eca2c7201/milestones/5fc51376a00c0951e4db7ace) at 9pm Jan 1. complete.
> > The [transaction](https://rinkeby.etherscan.io/tx/0x9e4c5be492b4e8bed6b3b750512152148cf2063dad446ebe1ec90acea9e82812) registered in Rinkeby blockchain aroung 9 pm Jan 1
> > Horus Requested Review was displayed 3 pm Ja 3!!
> > ![image](https://user-images.githubusercontent.com/65175075/103486367-93253880-4e12-11eb-83e6-15d73c70c021.png)
> > Then sunny (as reviewer) saw approve button.
> > This 2 days delay is normal.

@horus2021 I meant for some reason feathers has not received or processed the related events for two days. We may restarted server after two days and the conversation created.
