### ISSUE TITLE
Get `No record found for id` error when signing in with keystore wallet

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#34]
Reproduce:

1. `rm -rf data`
2. Empty localstorage for the Giveth app
3. `node --harmony deploy.js`
4. load the Dapp
5. Go to sign in, load `testrpcDeterministicAccount0.json` from Giveth-Dapp repro

Now you will get this error:
```
info: after: authentication/challenges - Method: create
info: error: authentication - Method: create: Challenge = k2KWCVXhwC3rgHQgyMGH
error:  NotAuthenticated: Challenge = k2KWCVXhwC3rgHQgyMGH
    at NotAuthenticated (/Users/satya/Development/feathers-giveth/node_modules/feathers-errors/lib/index.js:100:17)
    at /Users/satya/Development/feathers-giveth/node_modules/feathers-authentication/lib/hooks/authenticate.js:102:31
    at <anonymous>
info: after: authentication/challenges - Method: get
info: error: users - Method: get: No record found for id '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1'
error:  NotFound: No record found for id '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1'
    at NotFound (/Users/satya/Development/feathers-giveth/node_modules/feathers-errors/lib/index.js:121:17)
    at /Users/satya/Development/feathers-giveth/node_modules/feathers-nedb/lib/index.js:146:17
    at <anonymous>
```

**Comment by perissology** [comment]
from previous slack conversation...

> so the errors in feathers are more just warnings and are in the feathers-hooks that we are using. they aren’t causing issues and the only way to get rid of them is to rewrite the feathers hooks.

> The `NotAuthenticated: Challenge ...` error is b/c we 1st fail the authentication attempt and issue a challenge msg to sign.

> The `NotFound:` error is the default feathers logging b/c we are trying to get a user that doesn’t exist yet. We catch this error and create the user if it happens.

> It’s a bummer that the feathers logs are confusing, as they are logged on the individual service level. So if I call 1 service from another and catch the error, it still gets logged
