### ISSUE TITLE
Simulation script didn't patch exists donation, not removed after creating similar one

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#344]
![image](https://user-images.githubusercontent.com/5684607/103668116-043c2b80-4f8c-11eb-9f91-0109792effb4.png)

**Comment by aminlatifi** [comment]
They are for milestone https://beta.giveth.io/campaigns/5b39d45e14cec916d00dab20/milestones/5ff315312d93392e76e6b6db

**Comment by aminlatifi** [comment]
@mohammadranjbarz After vacation we will focus on new simulation script (typescript) and will fix all these on that.

**Comment by aminlatifi** [comment]
@mohammadranjbarz Does new patches solve this?

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I exactly dont know how to test it, 
 I would appreciate if you explain the test scenario then I'll test it and give you the details

**Comment by aminlatifi** [comment]
@mohammadranjbarz It was on beta, 
I will send you oldest db back we have to run the test. If you couldn't reproduce the above situation we should close this issue because it has been fixed now but maybe by running simulation script multiple times.

**Comment by aminlatifi** [comment]
Today we had a problem on beta, a donation `isMined` filed was false and simulation script didn't path it/

**Comment by mohammadranjbarz** [comment]
> Today we had a problem on beta, a donation `isMined` filed was false and simulation script didn't path it.

I simulate it on my system ( by manually change `mined:false`) to see what will happen and fix it

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I didnt see this issue in the giveth-1-simulation
And the redundant donations will removing from DB, 
I think we can assume it's done
