### ISSUE TITLE
Irrelevant query to milestone service on delegating from DAC

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#347]
On delegating donation from a DAC to a Milestone some query is executed against milestone service and produces errors like this:
```
6|feathers | 2021-01-06 15:15: info: milestones - No record found for id '5df9df79b468b627fc3fa78e'
6|feathers | 2021-01-06 15:15: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
6|feathers | NotFound: No record found for id '5df9df79b468b627fc3fa78e'
6|feathers |     at new NotFound (/home/deploy/feathers-giveth-develop/node_modules/@feathersjs/errors/lib/index.js:114:17)
6|feathers |     at modelQuery.lean.exec.then.data (/home/deploy/feathers-giveth-develop/node_modules/feathers-mongoose/lib/service.js:151:17)
```

**Comment by aminlatifi** [comment]
> On delegating donation from a DAC to a Milestone some query is executed against milestone service and produces errors like this:
> 
> ```
> 6|feathers | 2021-01-06 15:15: info: milestones - No record found for id '5df9df79b468b627fc3fa78e'
> 6|feathers | 2021-01-06 15:15: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
> 6|feathers | NotFound: No record found for id '5df9df79b468b627fc3fa78e'
> 6|feathers |     at new NotFound (/home/deploy/feathers-giveth-develop/node_modules/@feathersjs/errors/lib/index.js:114:17)
> 6|feathers |     at modelQuery.lean.exec.then.data (/home/deploy/feathers-giveth-develop/node_modules/feathers-mongoose/lib/service.js:151:17)
> ```

The missing point is that in this case '5df9df79b468b627fc3fa78e' is the Id of DAC which is the source of delegation

**Comment by aminlatifi** [comment]
@mdehghani Mohammad knows the reason, I assigned it to him

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
it was because of this line:
` await app.service('milestones').get(pledge.delegateTypeId || pledge.ownerTypeId);`
That deleted in the PR and Itested locally ( delegate from DAC to campaign and delegate from DAC to milestone) and I didnt see the error)
