### ISSUE TITLE
only display campaign w/ reviewer addresses in whitelist

### ISSUE THREAD

**Issue by perissology** [Giveth/feathers-giveth#38]

**Comment by jlecren** [comment]
Hi @perissology !

I'm starting to get into the code so sorry if I sounds dumb ;)

Do you imply to filter out the campaigns with an invalid reviewer from "Campaigns.find"? Like what does the hook "isProjectAllowed()" in "Campaigns.create" ?

**Comment by perissology** [comment]
this was actually already implemented in the `isProjectAllowed` hook. Since we don't add invalid campaigns, there's no need to filter them out.

sorry about that

**Comment by jlecren** [comment]
Problem solved then :-)
