### ISSUE TITLE
Wrong donation entities are created in Beta

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#382]
Multiple donations like below are created in beta db, causes repetitive processing the corresponding event. These donations have zero value in their `amount` and `pledgeId`. In fact there another correct donation for the tx with correct values exists, but these one are erroneous .

```
{
  "_id": {
    "$oid": "602063216c9d0a5f4b4f495e"
  },
  "status": "Committed",
  "mined": false,
  "parentDonations": [
    "6006143d25de2806b1db8c7d"
  ],
  "isReturn": false,
  "lessThanCutoff": true,
  "usdValue": 0,
  "txHash": "0x89d8f770e32fa8c541b19be3f664a78ae0ac125a8246151a9dfc89c70ec5ba67",
  "amount": "0",
  "amountRemaining": "0",
  "giverAddress": "0xDF290293C4A4d6eBe38Fd7085d7721041f927E0a",
  "pledgeId": "0",
  "comment": "",
  "ownerId": {
    "$numberLong": "2442"
  },
  "ownerTypeId": "601fc6dc6c9d0a5f4b4f489d",
  "ownerType": "milestone",
  "actionTakerAddress": "0x567355f84d44a982629D8675AB4aadBB92dbfD54",
  "tokenAddress": "0x6b175474e89094c44da98b954eedeac495271d0f",
  "createdAt": {
    "$date": "2021-02-07T22:01:05.770Z"
  },
  "updatedAt": {
    "$date": "2021-02-07T22:01:05.917Z"
  },
  "__v": 0
}
```

**Comment by mohammadranjbarz** [comment]
- [ ] Whats the initial status for delegated donations (When user delegates the new donation created at the moment or after the event is processed)
- [ ] If the initial status of delegated donations are `Pending` something is wrong in the backend which didn't set `mined` flag true
- [ ] If the initial status of delegated donations are `Committed` we should investigate the frontend or change the flow

**Comment by mohammadranjbarz** [comment]
https://github.com/Giveth/giveth-dapp/blob/1e0077500c5a454bd9b4d6aab5cf74c45e013830/src/services/DonationService.jsx#L254-L271

As you can see in code, whe delegate is successful then frontend create a `Committed` donation with mined `false` then backend after processing event update that `Committed` status.

@aminlatifi

**Comment by mohammadranjbarz** [comment]
![image.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/fa75acd9-6cf7-43c9-8e99-ac77f15df118)

**Comment by aminlatifi** [comment]
As I and @mohammadranjbarz found the root cause is that we have a bug in saving network events which ended up saving and processing one event multiple times.
@mohammadranjbarz please do these actions
- [ ] Find the best way to prevent saving one event multiple times, as you mentioned the best solution maybe adding unique index to event schema on the combination of fields blockNumber, transactionIndex and logIndex.
- [ ] Investigate why simulation script had not clear those redundant donations (status is Committed and mined is false)
- [ ] Clear footprints from milestones conversations

**Comment by mohammadranjbarz** [comment]
@aminlatifi  I've deleted the repetitive conversations in this milestone:
https://beta.giveth.io/campaigns/5feb2ca1dae3134bd0166dd6/milestones/6019a79ef9e6e877930e9667

And I think the simulation didn't fix the donations because I deployed the `giveth-1-simulation` after this problem so it's not worth to investigate the old simulation script

**Comment by aminlatifi** [comment]
@mohammadranjbarz Let's finalize our decision for this issue and implement it

**Comment by mohammadranjbarz** [comment]
@aminlatifi How about closing this issue?
