### ISSUE TITLE
Update Milestone model

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#4]
Can we include the following fields in the milestone model, as per the mock:

- image (base64)
- video url (string)
- description (string)
- owner (string)
- reviewers [string]
- status [enum?]
- causeID (string)

**Comment by ojones** [comment]
There is no pre-defined schema just add and remove whatever you want using featherjs service methods (link in readme under usage and help).

**Comment by perissology** [comment]
we will define a schema later
