### ISSUE TITLE
donation counters can be easily gamed

### ISSUE THREAD

**Issue by perissology** [Giveth/feathers-giveth#42]
We should update the donation counters if a donation is refunded, otherwise it's possible for someone to keep donating and refunding to make their dac look better

**Comment by satyavh** [comment]
I've been looking into this a little, thought it was a nice study task, but I hope you can help me out.  I see the transfer event being handled, but how can we know in feathers from the LP events that a donation is refunded?

**Comment by satyavh** [comment]
So Transfer gives back the idGiver, but that could be "2" right?
In the donations.db we store the `owner` as the idGiver (I think)
But there could (will) be multiple matching records. 

The only thing I can see that makes each record matching the data coming back from the `Transfer` event, is the donation amount. But amount isn't unique either. 

So I don't see how we can find the matching donation and revert it.

**Comment by perissology** [comment]
also need to update the donation counters if an `intendedProject` is rejected

**Comment by perissology** [comment]
this is fixed
