### ISSUE TITLE
Bridge  Doesn't return paymentTransactionHash

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/feathers-giveth#424]
`paymentTransactionHash` field was added about 2-3 weeks ago, but it's not in response anymore

ttps://feathers.bridge.beta.giveth.io/payments?event.returnValues.reference=0x628b82512c40cbe83b8461d92b7191847720835bf311cc493469f74e02db838f

**Comment by aminlatifi** [comment]
@mohammadranjbarz 
https://feathers.bridge.beta.giveth.io/payments?event.returnValues.reference=0x628b82512c40cbe83b8461d92b7191847720835bf311cc493469f74e02db838f

The response includes:
```
      "paymentTransactionHash": "0xa47d449c18fea54b9f6bd7084bdf918b5532d9b47392a603a1999bbeaa2281c0"
```

Is it what you mean?
