### ISSUE TITLE
Revise failed issues on beta 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#441]
Due to some change in email, `ProjectAdded` events end up having failed status after are processed. 

#437

**Comment by mohammadranjbarz** [comment]
It's the event:

```
{
    "_id" : ObjectId("60590e74088f957fed2060fa"),
    "topics" : [],
    "status" : "Failed",
    "address" : "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
    "blockNumber" : 8281045,
    "transactionHash" : "0x31ee03c0a7d75b4d38ae6d7269256f6d720cf81a449e3a292f5b59cffbe6245a",
    "transactionIndex" : 6,
    "blockHash" : "0x1f237af1b6f5eaee9cb0dd600b7b5f53f6db0b762dde061431b5008d048930f6",
    "logIndex" : 7,
    "id" : "log_a2aa1e94",
    "returnValues" : {
        "0" : "2533",
        "1" : "/ipfs/QmTWyrRgFTALD7Si45su4J37Hyc3u7QHYFJVj3Tza8CWKL",
        "idProject" : "2533",
        "url" : "/ipfs/QmTWyrRgFTALD7Si45su4J37Hyc3u7QHYFJVj3Tza8CWKL"
    },
    "event" : "ProjectAdded",
    "signature" : "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d",
    "raw" : {
        "data" : "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000342f697066732f516d5457797252674654414c4437536934357375344a3337487963337537514859464a566a33547a613843574b4c",
        "topics" : [ 
            "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d", 
            "0x00000000000000000000000000000000000000000000000000000000000009e5"
        ]
    },
    "confirmations" : 6,
    "createdAt" : ISODate("2021-03-22T21:39:00.509Z"),
    "updatedAt" : ISODate("2021-03-22T21:39:01.872Z"),
    "__v" : 0,
    "processingError" : "TypeError: Cannot read property 'email' of undefined"
}
```

**Comment by aminlatifi** [comment]
@mohammadranjbarz 
These events are still failed in beta:
```
/* 1 */
{
    "_id" : ObjectId("60590e74088f957fed2060fa"),
    "topics" : [],
    "status" : "Failed",
    "address" : "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
    "blockNumber" : 8281045,
    "transactionHash" : "0x31ee03c0a7d75b4d38ae6d7269256f6d720cf81a449e3a292f5b59cffbe6245a",
    "transactionIndex" : 6,
    "blockHash" : "0x1f237af1b6f5eaee9cb0dd600b7b5f53f6db0b762dde061431b5008d048930f6",
    "logIndex" : 7,
    "id" : "log_a2aa1e94",
    "returnValues" : {
        "0" : "2533",
        "1" : "/ipfs/QmTWyrRgFTALD7Si45su4J37Hyc3u7QHYFJVj3Tza8CWKL",
        "idProject" : "2533",
        "url" : "/ipfs/QmTWyrRgFTALD7Si45su4J37Hyc3u7QHYFJVj3Tza8CWKL"
    },
    "event" : "ProjectAdded",
    "signature" : "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d",
    "raw" : {
        "data" : "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000342f697066732f516d5457797252674654414c4437536934357375344a3337487963337537514859464a566a33547a613843574b4c",
        "topics" : [ 
            "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d", 
            "0x00000000000000000000000000000000000000000000000000000000000009e5"
        ]
    },
    "confirmations" : 6,
    "createdAt" : ISODate("2021-03-22T21:39:00.509Z"),
    "updatedAt" : ISODate("2021-03-22T21:39:01.872Z"),
    "__v" : 0,
    "processingError" : "TypeError: Cannot read property 'email' of undefined"
}

/* 2 */
{
    "_id" : ObjectId("60590ece088f957fed206100"),
    "topics" : [],
    "status" : "Failed",
    "address" : "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
    "blockNumber" : 8281050,
    "transactionHash" : "0x77518d75db705dde40e5c7d3d49e59a6a704a7b8c12f8b7a82561847bcafe6b6",
    "transactionIndex" : 6,
    "blockHash" : "0xb2a6a35220d127545e6ab196920f649dde516867b495ff19455cf4a018d182df",
    "logIndex" : 4,
    "id" : "log_145406f1",
    "returnValues" : {
        "0" : "2534",
        "1" : "/ipfs/QmXgQAXs73J3UNgrarpY34oJiGBNUM2Sub4Lj1BTqD8kF6",
        "idProject" : "2534",
        "url" : "/ipfs/QmXgQAXs73J3UNgrarpY34oJiGBNUM2Sub4Lj1BTqD8kF6"
    },
    "event" : "ProjectAdded",
    "signature" : "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d",
    "raw" : {
        "data" : "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000342f697066732f516d58675141587337334a33554e67726172705933346f4a6947424e554d32537562344c6a3142547144386b4636",
        "topics" : [ 
            "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d", 
            "0x00000000000000000000000000000000000000000000000000000000000009e6"
        ]
    },
    "confirmations" : 6,
    "createdAt" : ISODate("2021-03-22T21:40:30.114Z"),
    "updatedAt" : ISODate("2021-03-22T21:40:30.774Z"),
    "__v" : 0,
    "processingError" : "TypeError: Cannot read property 'email' of undefined"
}

/* 3 */
{
    "_id" : ObjectId("60591108088f957fed206151"),
    "topics" : [],
    "status" : "Failed",
    "address" : "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
    "blockNumber" : 8281088,
    "transactionHash" : "0xa2034f5d2c1c09f5a811ee6a72e740631d7d1686f4959079f7e7e584493444c9",
    "transactionIndex" : 5,
    "blockHash" : "0xb2ccaa908524a601b1d0f49db4c19d6b5b7b57995a16d08f3ef97036d4dc9898",
    "logIndex" : 1,
    "id" : "log_45303048",
    "returnValues" : {
        "0" : "2536",
        "1" : "/ipfs/QmR87rXH2Qn1CBVtLUA7WadEaDmFmBjK2PenmHvxkHUJgU",
        "idProject" : "2536",
        "url" : "/ipfs/QmR87rXH2Qn1CBVtLUA7WadEaDmFmBjK2PenmHvxkHUJgU"
    },
    "event" : "ProjectAdded",
    "signature" : "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d",
    "raw" : {
        "data" : "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000342f697066732f516d52383772584832516e31434256744c5541375761644561446d466d426a4b3250656e6d4876786b48554a6755",
        "topics" : [ 
            "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d", 
            "0x00000000000000000000000000000000000000000000000000000000000009e8"
        ]
    },
    "confirmations" : 6,
    "createdAt" : ISODate("2021-03-22T21:50:00.115Z"),
    "updatedAt" : ISODate("2021-03-22T21:50:00.955Z"),
    "__v" : 0,
    "processingError" : "TypeError: Cannot read property 'email' of null"
}
```

**Comment by aminlatifi** [comment]
> @mohammadranjbarz
> These events are still failed in beta:
> 
> ```
> /* 1 */
> {
>     "_id" : ObjectId("60590e74088f957fed2060fa"),
>     "topics" : [],
>     "status" : "Failed",
>     "address" : "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
>     "blockNumber" : 8281045,
>     "transactionHash" : "0x31ee03c0a7d75b4d38ae6d7269256f6d720cf81a449e3a292f5b59cffbe6245a",
>     "transactionIndex" : 6,
>     "blockHash" : "0x1f237af1b6f5eaee9cb0dd600b7b5f53f6db0b762dde061431b5008d048930f6",
>     "logIndex" : 7,
>     "id" : "log_a2aa1e94",
>     "returnValues" : {
>         "0" : "2533",
>         "1" : "/ipfs/QmTWyrRgFTALD7Si45su4J37Hyc3u7QHYFJVj3Tza8CWKL",
>         "idProject" : "2533",
>         "url" : "/ipfs/QmTWyrRgFTALD7Si45su4J37Hyc3u7QHYFJVj3Tza8CWKL"
>     },
>     "event" : "ProjectAdded",
>     "signature" : "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d",
>     "raw" : {
>         "data" : "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000342f697066732f516d5457797252674654414c4437536934357375344a3337487963337537514859464a566a33547a613843574b4c",
>         "topics" : [ 
>             "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d", 
>             "0x00000000000000000000000000000000000000000000000000000000000009e5"
>         ]
>     },
>     "confirmations" : 6,
>     "createdAt" : ISODate("2021-03-22T21:39:00.509Z"),
>     "updatedAt" : ISODate("2021-03-22T21:39:01.872Z"),
>     "__v" : 0,
>     "processingError" : "TypeError: Cannot read property 'email' of undefined"
> }
> 
> /* 2 */
> {
>     "_id" : ObjectId("60590ece088f957fed206100"),
>     "topics" : [],
>     "status" : "Failed",
>     "address" : "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
>     "blockNumber" : 8281050,
>     "transactionHash" : "0x77518d75db705dde40e5c7d3d49e59a6a704a7b8c12f8b7a82561847bcafe6b6",
>     "transactionIndex" : 6,
>     "blockHash" : "0xb2a6a35220d127545e6ab196920f649dde516867b495ff19455cf4a018d182df",
>     "logIndex" : 4,
>     "id" : "log_145406f1",
>     "returnValues" : {
>         "0" : "2534",
>         "1" : "/ipfs/QmXgQAXs73J3UNgrarpY34oJiGBNUM2Sub4Lj1BTqD8kF6",
>         "idProject" : "2534",
>         "url" : "/ipfs/QmXgQAXs73J3UNgrarpY34oJiGBNUM2Sub4Lj1BTqD8kF6"
>     },
>     "event" : "ProjectAdded",
>     "signature" : "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d",
>     "raw" : {
>         "data" : "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000342f697066732f516d58675141587337334a33554e67726172705933346f4a6947424e554d32537562344c6a3142547144386b4636",
>         "topics" : [ 
>             "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d", 
>             "0x00000000000000000000000000000000000000000000000000000000000009e6"
>         ]
>     },
>     "confirmations" : 6,
>     "createdAt" : ISODate("2021-03-22T21:40:30.114Z"),
>     "updatedAt" : ISODate("2021-03-22T21:40:30.774Z"),
>     "__v" : 0,
>     "processingError" : "TypeError: Cannot read property 'email' of undefined"
> }
> 
> /* 3 */
> {
>     "_id" : ObjectId("60591108088f957fed206151"),
>     "topics" : [],
>     "status" : "Failed",
>     "address" : "0x8eB047585ABeD935a73ba4b9525213F126A0c979",
>     "blockNumber" : 8281088,
>     "transactionHash" : "0xa2034f5d2c1c09f5a811ee6a72e740631d7d1686f4959079f7e7e584493444c9",
>     "transactionIndex" : 5,
>     "blockHash" : "0xb2ccaa908524a601b1d0f49db4c19d6b5b7b57995a16d08f3ef97036d4dc9898",
>     "logIndex" : 1,
>     "id" : "log_45303048",
>     "returnValues" : {
>         "0" : "2536",
>         "1" : "/ipfs/QmR87rXH2Qn1CBVtLUA7WadEaDmFmBjK2PenmHvxkHUJgU",
>         "idProject" : "2536",
>         "url" : "/ipfs/QmR87rXH2Qn1CBVtLUA7WadEaDmFmBjK2PenmHvxkHUJgU"
>     },
>     "event" : "ProjectAdded",
>     "signature" : "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d",
>     "raw" : {
>         "data" : "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000342f697066732f516d52383772584832516e31434256744c5541375761644561446d466d426a4b3250656e6d4876786b48554a6755",
>         "topics" : [ 
>             "0x9958fc92731727637b02f1ac1e6caf2814442c27e1d962f0c477cd14280f586d", 
>             "0x00000000000000000000000000000000000000000000000000000000000009e8"
>         ]
>     },
>     "confirmations" : 6,
>     "createdAt" : ISODate("2021-03-22T21:50:00.115Z"),
>     "updatedAt" : ISODate("2021-03-22T21:50:00.955Z"),
>     "__v" : 0,
>     "processingError" : "TypeError: Cannot read property 'email' of null"
> }
> ```

Seems intended projects are activated by simulation script, so everything is OK

**Comment by mohammadranjbarz** [comment]
I changed the status of these events to `Processed` in DB manually

[https://app.zenhub.com/files/99012473/ac093d8a-c7a7-404a-a135-6a2fc1f86b54/download](https://app.zenhub.com/files/99012473/ac093d8a-c7a7-404a-a135-6a2fc1f86b54/download)

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
Did you mean this or something else should I do?

**Comment by mohammadranjbarz** [comment]
The 2020 and 2021 `Failed` events changed to `Processed` (because all of the related milestones were `Paid` or `Completed`
@aminlatifi 

https://feathers.beta.giveth.io/events?status=Failed
