### ISSUE TITLE
Create Trace user report

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#452]
Some script should be created to generate report like this doc:

https://docs.google.com/spreadsheets/d/1db4qNQ53lzbK2bY6i4wEKynTFGrHgRltDx4BckpNOvY/edit?usp=sharing

**Comment by mohammadranjbarz** [comment]
![Screen Shot 1400-01-11 at 14.00.01.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/09a8ea8f-0cb9-446a-9767-e49743751eb6)

@aminlatifi 
What does that mean `firstUse`  `lastUse` and `NOTE` columns?

**Comment by aminlatifi** [comment]
> ![Screen Shot 1400-01-11 at 14.00.01.png](https://camo.githubusercontent.com/fa552d33c46e1e904fd618e6ffd48fa500bdc069cabb14d16f627be5f8253c2f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566613765643766623039393433323364316136363033342f30396138656138662d306362392d343436612d393736372d653439373433373531656236)
> 
> @aminlatifi
> What does that mean `firstUse` `lastUse` and `NOTE` columns?
> 
> And for received milestones I should find milestones that user is recipient of that milestone, status of mielstone is important?
> just should check the `Paid` milestone?
> for reviewers as well

Sorry for late response,
About first use we can use transaction from fields, however it needs we fill transaction cache with all transactions (we may have it!)

**Comment by mohammadranjbarz** [comment]
@aminlatifi 

Sorry I deleted your comment by mistake, you said we can extract first use and last use from transactions colelction

**Comment by MoeNick** [comment]
Report generated but it's needed to be reviewed and discuss with @GriffGreen. 
number of campaign created, the original creator or the currant owner?

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I added a script to fill transactions table with fetching `events` and `donations` transactions
