### ISSUE TITLE
Some issue on backend causes feathers watch to not work

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#454]
New Donation subscription on front-end doesn't work sometimes. It's probably related to some issue on backend and sending email to user.

**Comment by aminlatifi** [comment]
@mohammadranjbarz Please check new donation badge in all kind of project after this feathers upgrade

**Comment by aminlatifi** [comment]
@mohammadranjbarz Please upgrade feathers-reactive package in giveth-dapp and then test.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Please upgrade feathers-reactive package in giveth-dapp and then test.

Sure I'll do it

**Comment by mohammadranjbarz** [comment]
As you may know we had two types of watching issues:
1. After some changing network and users and changing networks it may doesn't work
2. After upgrading feathers dependencies, the watch has stopped working completely

And in this issue I worked on second problem and it works now (Giveth/giveth-dapp#2125)

the below screenshots are for donations table after `delegate` and `donate`, and as you see without refreshing the donations badges appeared
![Screen Shot 1400-02-27 at 10 21 12](https://user-images.githubusercontent.com/9850545/118438747-14160a00-b6fa-11eb-90cc-ed4b545cbe8b.png)

![Screen Shot 1400-02-27 at 10 20 24](https://user-images.githubusercontent.com/9850545/118438730-0eb8bf80-b6fa-11eb-9502-cad9c2fec153.png)

<img width="1384" alt="Screen Shot 1400-02-27 at 10 36 39" src="https://user-images.githubusercontent.com/9850545/118439732-cb5f5080-b6fb-11eb-9d3f-23b8e1bebedc.png">

**Comment by MoeNick** [comment]
@mohammadranjbarz it works perfect. good job man
