### ISSUE TITLE
Finding a solution for when backend connection to db fails

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/feathers-giveth#461]

**Comment by MoeNick** [comment]
I think we can close this with sentry? Am I right @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Yeah I think so, 
I move it to UAT after showing it to you you can move it to done

related to #450

**Comment by MoeNick** [comment]
Thanks @mohammadranjbarz for the test:

Test Scenario:
1- MongoDB pass changed in config manually to occur a lost DB connection. 
2- Restart DB
3- We got an alert for a loss connection on Sentry. 

https://sentry.io/organizations/giveth-ds/issues/2506479187/events/ab55f4318e704cbeac010f2a09b341c4/?project=5853180

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/22e0d288-cc43-4ce7-bfab-7e0a4ed35a40)

_Originally posted by @MoeNick in https://github.com/Giveth/giveth-dapp/issues/2301#issuecomment-877796798_
