### ISSUE TITLE
Email of money moved to recipient wallet has incorrect sentence

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#465]
<img width="503" alt="Screen Shot 2021-04-06 at 12 12 24" src="https://user-images.githubusercontent.com/5684607/113676541-cad1a400-96d1-11eb-86e1-316c535abd4a.png">

When money finally moved to user wallet we send email to the recipient. It says
```
You can expect to see these payment(s) to arrive in your wallet <wallet address> within 48 - 72 hrs.
```
Which is incorrect, because money is already in user wallet

**Comment by aminlatifi** [comment]
It seems there is no template is defined for this email under #1700

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
No it's not about templates, my text is incorrect,
I'll fix that

**Comment by MoeNick** [comment]
I only can se this after collecting. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/0a449198-4686-4fc0-8741-129eb6d9c560)

**Comment by mohammadranjbarz** [comment]
> I only can se this after collecting.
> ![image.png](https://camo.githubusercontent.com/54f668223a0aa46730e015db75cc174504909e063d9ece5ab9244d3082006a61/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630346632343263323831396435646136343236616430332f30613434393139382d343638362d346663302d383734312d313239656236643963353630)

Your email is for collecting money, this issue is about payout (money goes to recipient wallet in mainnet)
So because it's about real money in mainnet you can't test it in UAT

**Comment by MoeNick** [comment]
@aminlatifi can you test it pls?
(Isn't there anyway we simulated main net processes over develop? )

**Comment by aminlatifi** [comment]
> @aminlatifi can you test it pls?
> (Isn't there anyway we simulated main net processes over develop? )

I had tested it once myself. It would be OK and can be closed.
