### ISSUE TITLE
Add simple monitoring to let us know if Feathers was down

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/feathers-giveth#470]
Uptimerobots check our API every 5 minutes and email to me if server was down

**Comment by mohammadranjbarz** [comment]
[Uploading... Screen Shot 1400-01-18 at 08.56.51.png]

**Comment by mohammadranjbarz** [comment]
<img width="1440" alt="Screen Shot 1400-01-18 at 08 56 51" src="https://user-images.githubusercontent.com/9850545/113810619-e4c9c000-977f-11eb-8552-7427be849e8c.png">

**Comment by MoeNick** [comment]
Do we still use it? Is it oprational?  @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> Do we still use it? Is it oprational?  @mohammadranjbarz 

Yes it's ok, it's a service that you can add your email, and put a url there, it will call that and if not getting answer, should notify you with email ( you can do it your self to monitor any url that you want)
but I cant get your point about, "is it operational?"

**Comment by mohammadranjbarz** [comment]
https://uptimerobot.com

**Comment by aminlatifi** [comment]
We have granafa 
@geleeroyale has set it up long time ago

**Comment by MoeNick** [comment]
@aminlatifi @mohammadranjbarz 
Just want to make sure we have a reliable tool and we get the notification ASAP. 
It would be fantastic if we simulate this failure and see if we get notification or not.
