### ISSUE TITLE
User authentication is necessary for proposing trace

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/feathers-giveth#543]
User should be authenticated to be able to propose a new trace.

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
We authentication for all create methods https://github.com/Giveth/feathers-giveth/blob/aed79280c1684bffb668b5fd88d5e76196683db4/src/app.hooks.js#L25-L33

but we don't check the ownerAddress of trace be equal to the user's wallet Address,,
I think it's better to add this checking,
@aminlatifi  what do you think?

**Comment by aminlatifi** [comment]
> @aminlatifi
> We authentication for all create methods
> 
> https://github.com/Giveth/feathers-giveth/blob/aed79280c1684bffb668b5fd88d5e76196683db4/src/app.hooks.js#L25-L33
> 
> but we don't check the ownerAddress of trace be equal to the user's wallet Address,,
> I think it's better to add this checking,
> @aminlatifi what do you think?

This is the implementation of `authenticate`:
https://github.com/Giveth/feathers-giveth/blob/aed79280c1684bffb668b5fd88d5e76196683db4/src/app.hooks.js#L6-L11
