### ISSUE TITLE
Do we have Sentry account?  needing add a project for feathers-giveth

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/feathers-giveth#544]
We've added sentry to feathers-giveth for crash reporting, 
do we have sentry account for Giveth? if we have, please some one who is in charge create a project and give access to Trace Dev team to can see logs in sentry

**Comment by MoeNick** [comment]
Can we have your help @willyogo ?

**Comment by willyogo** [comment]
@MoeNick James F set up a Sentry account for Giveth.io a few months ago. I have the login info and will post it in the #env-sharing discord channel so you guys can log in and invite the Trace team

**Comment by mohammadranjbarz** [comment]
Thanks @willyogo 

@MoeNick  Now I and Amin have access to sentry, I can we close this issue
