### ISSUE TITLE
Improve Analytics Event Params

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/feathers-giveth#557]
To improve the analytics being sent we need to refine the information we're sending to segment from the track calls and to flatten nested properties into simple object names. 

Another discussion is if we would like to include things like user email addresses and/or names which would make integration with any new email or user outreach systems easier to implement further down the road..definitely if we're  integrating TRACE with .io we should be gathering similar information from users...  input from @aminlatifi  and @MoeNick   would be appreciated

**Comment by divine-comedian** [comment]
More Context on flattening properties - 


this is an example of a track call from the impact-graph on .io in the `const segmentDonationReceived` we define specifically the information we want and save it to an object with simple property names mapped to their value in the DB. We then put this object inside of the track call for the specific event we want to attach it to.
#### Save Donation

```


const projectOwner = await User.findOne({ id: Number(project.admin) })

        if (projectOwner) {

          await tokenValues

          analytics.identifyUser(projectOwner)

          const segmentDonationReceived = {
            email: projectOwner.email,
            title: project.title,
            firstName: projectOwner.firstName,
            projectOwnerId: project.admin,
            slug: project.slug,
            amount: Number(amount),
            transactionId: transactionId.toString().toLowerCase(),
            transactionNetworkId: Number(transactionNetworkId),
            currency: token,
            createdAt: new Date(),
            toWalletAddress: toAddress.toString().toLowerCase(),
            fromWalletAddress: fromAddress.toString().toLowerCase(),
            donationValueUsd: donation.valueUsd,
            donationValueEth: donation.valueEth
          }

          analytics.track(
            'Donation received',
            projectOwner.segmentUserId(),
            segmentDonationReceived,
            projectOwner.segmentUserId()
            )
        }
 ```

 we specify all the information we want to capture and assign an object with flattened property names that get the information we want. It should come out clean on the segment side like this: 

```
analytics.track({
  anonymousId: 'givethId-161',
  userId: 'givethId-161',
  event: 'Donation received',
  properties: {
    amount: 0.001,
    createdAt: new Date('2021-07-08T12:41:36.526Z'),
    currency: 'ETH',
    donationValueEth: 0.001,
    donationValueUsd: 2.17127,
    email: 'mrnikkhah@gmail.com',
    firstName: 'Moe',
    fromWalletAddress: '0x62f49a875f09c82e104197afbb8a30e66bb96ba3',
    projectOwnerId: '161',
    slug: 'myfirstprojectonio',
    title: 'MyFirstProjectOnIO',
    toWalletAddress: '0xf3bab2f1add2af035f489d7f3fb45a2411ed89ba',
    transactionId: '0x0ddd1a41af785ea73a54073a669456303adafba99f53183324fa2911043b656c',
    transactionNetworkId: 3
  }
});
```

**Comment by divine-comedian** [comment]
Here's a list of properties I think we should include for each event on TRACE, if anything is unclear, incomplete or inconsistent please reach out @mohammadranjbarz 


@aminlatifi  @MoeNick 
**add emails to all calls? 
add names to all calls?**

- Donation 
        - slug
        - transactionID
        - DonorID
        - Donor Address
        - DonorName
        - Amount
        - Currency
        - valueUSD
        - valueEth
        - OwnerAddress
        - OwnerName
        - entityType
        - entityTitle
        - traceType (if applicable)

- Trace Withdraw
        - slug
        - traceType
        - currency 
        - amount 
        - valueUSD
        - valueEth
        -  traceRecipientAddress
        -  reviewerAddress
        -  reviewerID
    
- Trace Create
    - slug
    - title
    - ownerID
    - traceType
    - traceID
     - traceRecipientAddress
    - parentCampaignTitle
    - parentCampaignID
    - parentCampaignAddress
    -  reviewerAddress
    -  reviewerID

- Trace Accepted 
    - title
    - slug
    - traceOwnerID
    - traceOwnerName
    - traceOwnerAddress
    - traceRecipientAddress
    - parentCampaignTitle
    - parentCampaignID
    - parentCampaignAddress
    -   reviewerAddress
    -  reviewerID
    
- Approve Trace 
    - title
    - slug
    - traceType
    -  traceOwnerID
    -  traceOwnerAddress
    -  traceRecipientAddress
    - parentCampaignTitle
    - parentCampaignID
    - parentCampaignAddress
    -  reviewerAddress
    -  reviewerID

- Trace Cancelled
    -    fix mispelling
    -    title
    -    slug
    -   traceType
    -   traceOwnerID
    -   traceOwnerAddress
    -   traceRecipientAddress
    -   parentCampaignTitle
    -   parentCampaignID
    -   parentCampaignAddress
     -  reviewerAddress
    -  reviewerID

- Campaign Created
    - slug
    - title
    - ownerID
    - campaignID
    - campaignAddress
    -   reviewerAddress
     -  reviewerID

- Donated to Community
        - title
        -slug
         - transactionID
        - donorID
        - donorAddress
        - donorName?
        - donorEmail?
        - amount
        - currency
        - valueUSD
        - valueEth
        - communityAddress
        - communityID
        - communityOwnerName?
        - communityOwnerEmail?
         
- Community Created
        - title
        - slug
        - ownerID
        - communityID
        - communityAddress

- Rejected Donation
     *fires when I cancel the donation in Metamask
    - slug
    - donorAddress
    - donorID
    - amount
    - currency
    - valueUsd
    - valueEth
    - title
    - parentCampaignTitle
    - parentCampaignAddress

- Delegated
    - parentEntityTitle
    - parentEntityAddress
    - parentEntityOwnerID
    - parentEntityID
    - parentEntitySlug
    - parentEntityType
    - currency
    - amount
    - valueUSD
    - valueEth
    - transactionID
    - entityTitle
    - entityAddress
    - entityID
    - entitySlug
    - entityType
    - entityOwnerID
    - traceType (if applicable)

- Campaign Cancelled
    - fix event mispelling
    - title
    - slug
    - ownerID
    - campaignID
    - campaignAddress

**Comment by mohammadranjbarz** [comment]
@MoeNick 
I think we should move this issue to sprint backlog and start implementing, 
am I right?

**Comment by MoeNick** [comment]
@mohammadranjbarz We would better make a copy and new estimates...

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz We would better make a copy and new estimates...

It's new issue,
(Mitch has created this yesterday)
I put the estimate

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
Now you can test the changes on event params in here:
https://deploy-preview-2399--giveth-dapp.netlify.app (or you can run #2399 locally)
the changes that you wanted almost done except some items:
somewhere you said the `parentCampaignAddress` but I didn't understand what you mean, do you mean campaignLink in giveth-dapp?
or for example `reviewerId`, for users we have address and the `reviewerAddress` is enough ( actually we don't use id field for user never). or somewhere you wanted `campaignSlug` but at that point that we fire event we just have id of campaign, for getting slug we should send another request to get the campaign slug that I think it doesn't worth to do,

Anyway please, test it and say to me if there is something missing


<img width="1239" alt="Screen Shot 1400-04-27 at 23 44 21" src="https://user-images.githubusercontent.com/9850545/126106434-300b4772-3e34-4c8f-beb7-20040c5f767b.png">

**Comment by divine-comedian** [comment]
@mohammadranjbarz 
`parentCampaignAddress` would be the wallet address of the parent Campaign
`reviewerID` would be so we can alias if the reviewer is the same user somewhere else on TRACE, assuming the user ID is the same for any entity or role they become... 
campaignSlug will be important to have for if we later want to integrate with autopilot.

I'll start testing now!

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
Thanks mitch, the changes are on `UAT`, campaigns have wallet address? 
I should talk about it with you in DM

**Comment by divine-comedian** [comment]
- [ ]  Donation 
        - [ ]  slug - missing - change name to entitySlug
        - transactionID - good
        - [ ]  DonorID - missing
        - Donor Address - good
        - DonorName - good
        - Amount - good
        - Currency - good
        - valueUSD - good
        - [ ]  valueEth - missing
        - [ ]  OwnerAddress - change name to entityOwnerAddress for clarity
        - [ ]  OwnerName - missing
        - entityType - good- 
        - entityTitle - good
        - [ ]  traceType (if applicable) - missing

- Trace Withdraw
        - [ ]  slug - missing - change to entitySlug
        - traceType - good
        - currency - good
        - amount  - good 
        - valueUSD - good
        - [ ]  valueEth - missing
        -  traceRecipientAddress - good
        -  reviewerAddress - good?
        -  reviewerID - see comments
    
- [ ]  Trace Create - **does not fire for bounty**
    - [ ]  slug - missing
    - title - good
    - [ ]  ownerID - change name to ownerAddress
    - traceType - good
    - traceID - good
     - [ ]  traceRecipientAddress - missing
    - parentCampaignTitle - good
    - parentCampaignID - good
    - [ ]  parentCampaignAddress - missing
    -  reviewerAddress - good
    -  reviewerID - see comments

- Trace Accepted 
    - title - good
    - [ ]  slug - missing
    - traceOwnerID - good
    - [ ]  traceOwnerName - missing
    - [ ]  traceOwnerAddress - this is userAddress? needs name change to keep standardized 
    - [ ]  traceRecipientAddress - not working - showed up as 0x000000....
    - parentCampaignTitle - good
    - [ ]  parentCampaignID - missing
    - parentCampaignAddress
    - [ ]   reviewerAddress - good
 
    
- Approve Trace 
    - title - good
    - [ ]  slug - missing
    - traceType - good
    - [ ]   traceOwnerID - change name to traceOwnerAddress 
    - [ ]  traceOwnerAddress -  see above 
    - [ ]  traceRecipientAddress - shows as 0x000000...
    - parentCampaignTitle - good
    - [ ]  parentCampaignID - see comments
    - [ ]  parentCampaignAddress - missing
    -  reviewerAddress - good
    



- Trace Marked Complete
    - title - good
- [ ]  slug - missing
    - traceType - good
    - [ ]   traceOwnerID - missing
   - [ ]    traceOwnerAddress - good, fix name to traceOwnerAddress
    - [ ]    traceRecipientAddress - shows as 0x0000000...
    - parentCampaignTitle - good
    - [ ]   parentCampaignID - missing
    - [ ]   parentCampaignAddress - missing
    -  reviewerAddress - good
    -  reviewerID - see comments

- Trace Cancelled
    - [ ]   remove  donationCounters from being captured
   - [ ]    fix mispelling
    -    title - good 
    - [ ]     slug - missing
    -   traceType - good
    - [ ]     traceOwnerID - change to traceOwnerAddress
    -   traceOwnerAddress - see above
    -   traceRecipientAddress - good
    -   parentCampaignTitle - good
      - [ ]  parentCampaignID - missing
 - [ ] parentCampaignAddress - missing
     -  reviewerAddress - good
    -  reviewerID - see comments

- Campaign Created
     - [ ] slug - missing
    - title - good
     - [ ] ownerID - this is userID?
     - [ ] campaignID - missing
     - [ ] campaignAddress - consolidate to ownerAddress - currently logged twice as ownerAddress and userAddress
    -   reviewerAddress - good
     -  reviewerID - see comments

- Donated to Community
        - title - good
        - [ ] slug - missing - entitySlug
         - transactionID - good
        - donorID - good
        - donorAddress
        - donorName? 
        - donorEmail?
        - amount - good
        - currency - good
        - valueUSD - good
        - [ ] valueEth - missing
         - [ ] communityAddress - change from donationOwnerAddress to entityOwnerAddress
        - communityID - good
        - communityOwnerName?
        - communityOwnerEmail?


         
- Community Created - event fires as Community Edited
         - [ ] title - needs to be fixed -  points to ownerAddress
         - [ ] slug - missing
         - [ ] ownerID - missing
         - [ ] communityID - missing
         - [ ] communityAddress - userAddress and ownerAddress is redundant log, keep just ownerAddress



- Delegated - Community to Campaign
    - parentEntityTitle - good
     - [ ] parentEntityAddress - this is logged as userAddress change label to parentEntityAddress
     - [ ] parentEntityOwnerID - missing
    - parentEntityID - good
    - parentEntitySlug - good
    - parentEntityType - good
    - currency - good
    - amount - good
    - valueUSD - good
     - [ ] valueEth - missing
    - transactionID - good
    - entityTitle - good
     - [ ] entityAddress - currently saved as userAddres - should be changed
    - entityID - good
    - entitySlug - good
     - [ ] entityType - says 'giver' when entity type was Campaign
    - entityOwnerID - good
    - traceType (if applicable)

- Delegated - Campaign to Trace
    - parentEntityTitle - good
     - [ ] parentEntityAddress - this is logged as userAddress change label to parentEntityAddress
     - [ ] parentEntityOwnerID - missing
    - parentEntityID - good
    - parentEntitySlug - good
    - parentEntityType - good
    - currency - good
    - amount - good
    - valueUSD - good
     - [ ] valueEth - missing
    - transactionID - good
    - entityTitle - good
     - [ ] entityAddress - missing - this is the entityOwnerAddress
    - entityID - good
     - [ ] entitySlug - missing
    - entityType - good
     - [ ] entityOwnerID - returns blank
     - [ ] traceType (if applicable) - **missing**
    
    - Delegated - Community to Trace
    - parentEntityTitle - good
     - [ ] parentEntityAddress - this is logged as userAddress change label to parentEntityAddress
     - [ ] parentEntityOwnerID - missing
     - [ ] parentEntityID - missing
    - parentEntitySlug - good
    - parentEntityType - good
    - currency - good
    - amount - good
    - valueUSD - good
     - [ ] valueEth - missing
    - transactionID - good
    - entityTitle - good
     - [ ] entityAddress - currently being saved as entityOwnerID - change to entityOwnerAddress
    - entityID - good
    - entitySlug - good
     - [ ] entityType - shows 'giver' when type was trace
     - [ ] entityOwnerID - see comments on entityAddress
    - traceType (if applicable) - good

- Campaign Cancelled
    - fix event mispelling - good
    - title - good
    - slug - good
     - [ ] ownerID - change name to ownerAddress
    - campaignID - good
     - [ ] campaignAddress - remove - replaced by ownerAddress

- Donate to Campaign
    -  amount - good
    -  currency - good
    -  donorName - good
     - [ ] donationOwnerAddress - change to entityOwnerAddress - currently being saved as same address as donorAddress
    -  donorAddress - good 
     - [ ] slug- missing
    -  title - good
    -  type - good
    -  usd value - good
    
There it is! I added checkboxes to all the things that need to be reviewed and fixed! let me know if you see anything else that I missed or isn't clear!

**Comment by mohammadranjbarz** [comment]
@divine-comedian  Thanks for testing,
* Donation: I dont know what should be the value of donorId, cause we have donorAddress
* Trace Accepted: bounties doesnt have recipientAddress in create time
* Trace Withdraw
- [x] slug - missing - change to entitySlug
- [x] valueEth - missing

* Donated to Community
- [x] slug - missing - entitySlug
- [x] valueEth - missing
- [ ] communityAddress - change from donationOwnerAddress to entityOwnerAddress ( I didnt get your point, now we have entityOwnerAddress, do we need communityAddress? because the donated events is general between trace, community, and campaign if you want to change entityOwnerAddress to communityAddress it needed some if-else that I think may make code dirty)

* Community  Created - event fires as Community Edited
- [x] title - needs to be fixed - points to ownerAddress
- [x] slug - missing
- [x] ownerID - missing ( we have it with name ownerAddress)
- [x] communityID - missing
- [x] communityAddress - userAddress and ownerAddress is redundant log, keep just ownerAddress ( when we send analytics data through backend in brave browser we need userAddress , so we should keep it)

* Donate to Campaign

 donationOwnerAddress : it's the addres of who donate, it's different from entityOwnerAddress

I have some question:
what is `entityAddress`? because we `entityOwnerAddress`, and `entityId` so what should we do
whats is `parentEntityAddress` while we have `parentEntityId` and `parentEntityOwnerAddress`
what should be `entityOwnerId` when we have `entityOwnerAddress`
what is `traceOwnerId` when we have `traceOwnerAddress`

**Comment by MoeNick** [comment]
@divine-comedian 
Hey Mitch, you can do the UAT I think. Lots of thanks.

**Comment by divine-comedian** [comment]
Had a follow up call with mohammad today, I will have time on wednesday hopefully to begin testing these fixes.

**Comment by divine-comedian** [comment]
Okay! Tested again all fixes, here's the final review: 

Donation to Community
 - inconsistent naming from usdValue to valueEth

Trace Withdraw 
 - missing traceType

Campaign Created 
 - same address is captured for campaignAddress, ownerAddress and userAddress - consolidate to campaignOwnerAddress and userAddress

Trace Create - good

Trace Accepted - too much info being sent , trace object being sent  - 

![image](https://user-images.githubusercontent.com/67759413/127239245-60ae8973-8b88-4444-8825-45758b4a2127.png)


Trace Rejected  - **no event showed up in segment**

Trace Cancelled - good

Trace Approved - Good

Donation to Trace (All donation events) - 
    - inconsistent naming from usdValue to valueEth

Community Created - good

Delegated Community to Campaign - change parentEntityOwnerId to parentEntityOwnerAddress

Delegated Community to Trace - change parentEntityOwnerId to parentEntityOwnerAddress

Delegated Campaign to Trace - change parentEntityOwnerId to parentEntityOwnerAddress

Donate to Campaign - good

Campaign Cancelled - good

**Comment by mohammadranjbarz** [comment]
> Okay! Tested again all fixes, here's the final review:
> 
> Donation to Community
> 
> * inconsistent naming from usdValue to valueEth
> 
> Trace Withdraw
> 
> * missing traceType
> 
> Campaign Created
> 
> * same address is captured for campaignAddress, ownerAddress and userAddress - consolidate to campaignOwnerAddress and userAddress
> 
> Trace Create - good
> 
> Trace Accepted - too much info being sent , trace object being sent -
> 
> ![image](https://user-images.githubusercontent.com/67759413/127239245-60ae8973-8b88-4444-8825-45758b4a2127.png)
> 
> Trace Rejected - **no event showed up in segment**
> 
> Trace Cancelled - good
> 
> Trace Approved - Good
> 
> Donation to Trace (All donation events) -
> - inconsistent naming from usdValue to valueEth
> 
> Community Created - good
> 
> Delegated Community to Campaign - change parentEntityOwnerId to parentEntityOwnerAddress
> 
> Delegated Community to Trace - change parentEntityOwnerId to parentEntityOwnerAddress
> 
> Delegated Campaign to Trace - change parentEntityOwnerId to parentEntityOwnerAddress
> 
> Donate to Campaign - good
> 
> Campaign Cancelled - good

@divine-comedian  Thanks Mitch.

@MoeNick 
As we talked before We should create a new task for fixing these items that Mitch mentioned, am I right?

**Comment by MoeNick** [comment]
@mohammadranjbarz Of course. I'll do it.

**Comment by divine-comedian** [comment]
Are there any updates on this issue? Does it need further testing or is it ready to deploy?

**Comment by MoeNick** [comment]
We dont plan for remained items in currant sprint cause we were full, will start it again from Tue, our next sprint.

**Comment by mohammadranjbarz** [comment]
> Okay! Tested again all fixes, here's the final review:
> 
> Donation to Community
> 
> * inconsistent naming from usdValue to valueEth
> 
> Trace Withdraw
> 
> * missing traceType
> 
> Campaign Created
> 
> * same address is captured for campaignAddress, ownerAddress and userAddress - consolidate to campaignOwnerAddress and userAddress
> 
> Trace Create - good
> 
> Trace Accepted - too much info being sent , trace object being sent -
> 
> ![image](https://user-images.githubusercontent.com/67759413/127239245-60ae8973-8b88-4444-8825-45758b4a2127.png)
> 
> Trace Rejected - **no event showed up in segment**
> 
> Trace Cancelled - good
> 
> Trace Approved - Good
> 
> Donation to Trace (All donation events) -
> - inconsistent naming from usdValue to valueEth
> 
> Community Created - good
> 
> Delegated Community to Campaign - change parentEntityOwnerId to parentEntityOwnerAddress
> 
> Delegated Community to Trace - change parentEntityOwnerId to parentEntityOwnerAddress
> 
> Delegated Campaign to Trace - change parentEntityOwnerId to parentEntityOwnerAddress
> 
> Donate to Campaign - good
> 
> Campaign Cancelled - good
So this the works I should do for this task
- [ ] Trace Rejected - no event showed up in segment

- [ ] Trace Accepted - too much info being sent , trace object being sent 

- [ ] Inconsistent naming from usdValue to valueEth (changing valueEth to ethValue)

- [ ] Delegated Community to Campaign - change parentEntityOwnerId to parentEntityOwnerAddress

- [ ] Delegated Community to Trace - change parentEntityOwnerId to parentEntityOwnerAddress

- [ ] Delegated Campaign to Trace - change parentEntityOwnerId to parentEntityOwnerAddress

**Comment by mohammadranjbarz** [comment]
> > Okay! Tested again all fixes, here's the final review:
> > Donation to Community
> > 
> > * inconsistent naming from usdValue to valueEth
> > 
> > Trace Withdraw
> > 
> > * missing traceType
> > 
> > Campaign Created
> > 
> > * same address is captured for campaignAddress, ownerAddress and userAddress - consolidate to campaignOwnerAddress and userAddress
> > 
> > Trace Create - good
> > Trace Accepted - too much info being sent , trace object being sent -
> > ![image](https://user-images.githubusercontent.com/67759413/127239245-60ae8973-8b88-4444-8825-45758b4a2127.png)
> > Trace Rejected - **no event showed up in segment**
> > Trace Cancelled - good
> > Trace Approved - Good
> > Donation to Trace (All donation events) -
> > 
> > * inconsistent naming from usdValue to valueEth
> > 
> > Community Created - good
> > Delegated Community to Campaign - change parentEntityOwnerId to parentEntityOwnerAddress
> > Delegated Community to Trace - change parentEntityOwnerId to parentEntityOwnerAddress
> > Delegated Campaign to Trace - change parentEntityOwnerId to parentEntityOwnerAddress
> > Donate to Campaign - good
> > Campaign Cancelled - good
> 
> Thanks to Mitch, these are the works I should do for this task
> 
> * [x]  Trace Rejected - no event showed up in segment
> * [x]  Trace Accepted - too much info being sent , trace object being sent
> * [x]  Inconsistent naming from usdValue to valueEth (changing valueEth to ethValue)
> * [x]  Delegated Community to Campaign - change parentEntityOwnerId to parentEntityOwnerAddress
> * [x]  Delegated Community to Trace - change parentEntityOwnerId to parentEntityOwnerAddress
> * [x]  Delegated Campaign to Trace - change parentEntityOwnerId to parentEntityOwnerAddress

@divine-comedian 
All items implemented, you can test those here: https://deploy-preview-2473--giveth-dapp.netlify.app

**Comment by divine-comedian** [comment]
Nice work @mohammadranjbarz  I tested all the issues you mentioned above. I found only one inconsistency with the `Trace Rejected` event. It is missing some properties compared to the `Trace Accepted` event: 

    ownerAddress: 
    parentCampaignAddress: 
    parentCampaignTitle: 
    slug: 
    traceOwnerAddress: 
    traceOwnerName: 
    txUrl:

**Comment by mohammadranjbarz** [comment]
> Nice work @mohammadranjbarz I tested all the issues you mentioned above. I found only one inconsistency with the `Trace Rejected` event. It is missing some properties compared to the `Trace Accepted` event:
> 
> ```
> ownerAddress: 
> parentCampaignAddress: 
> parentCampaignTitle: 
> slug: 
> traceOwnerAddress: 
> traceOwnerName: 
> txUrl: 
> ```
@divine-comedian 
You are right,
I added missing paramteres, you can check it here
https://deploy-preview-2483--giveth-dapp.netlify.app

PS: in proposing and rejecting traces all things happen in our DB, not blockchain, so we don't have any txUrl to send ( in accept is different there we have txUrl because after accepting we send trace to blockchain network)

**Comment by divine-comedian** [comment]
good! just tested it, everything looks perfect. 

![image](https://user-images.githubusercontent.com/67759413/129797311-2512453c-3a1d-4c1c-8677-44d5d907f374.png)

**Comment by mohammadranjbarz** [comment]
@divine-comedian Thanks man,

@MoeNick  I think you can move this issue to DONE
