### ISSUE TITLE
don't count repetitive title if the end of characters are not similar

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/feathers-giveth#569]

**Comment by aminlatifi** [comment]
We don't match if user put extra space at the beginning. Mongo has a feature in regex matching which supports ignoring spaces at the head, tail and middle of string
![telegram-cloud-photo-size-4-5767299385653311007-y](https://user-images.githubusercontent.com/5684607/127281173-3cc3d2c1-aeb4-4095-bcfd-df40f904a5f7.jpg)

**Comment by MoeNick** [comment]
I dont have any clue how to test it.
