### ISSUE TITLE
When making 2 donations in a row, it throws error

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#58]
Reproduce:

1. make a donation
2. make another donation 

Now testrpc throws `Runtime Error: invalid opcode` and the donation fails

**Comment by perissology** [comment]
my comment from another issue:

> So I'm not sure what the cause of this is, but I have ran into it before. I suspect web3, or web3-provider-engine as it has happened both via testrpc and mvp (parity ropsten node).

> If you immediately try again, it will successfully send the tx.

to be further investigated, but is a dapp issue, not feathers

**Comment by vsimetka** [comment]
I have encountered this one before but it seems to be stochastic. Sometimes it bugged out even when creating campaigns/dacs but got itself fixed after restarting feathers and dapp.

**Comment by satyavh** [comment]
So the error that I'm still getting is:

```
  Transaction: 0xdd41dbb04696e035d9e4cb93f2263cd449bf2be76deecde69a6ec2575afd49d8
  Gas usage: 197798
  Block Number: 15
  Block Time: Wed Dec 06 2017 10:40:05 GMT+0100 (CET)
  Runtime Error: invalid opcode
```

This issue happens both on alpha as well as local.

**Comment by perissology** [comment]
@satyavh @vojtechsimetka does this happen only w/ testrpc or has it happened on ropsten as well?

If either of you run into this on ropsten, can you send me the following info:

1. console error messages
2. txHash that failed
3. refresh page & try it again
4. the txHash of the second try, and if the second try failed or succeeded

I've just run into this on testrpc a few times. If I refresh the page, the tx works on the 2nd attempt. It seems to be a gas issue even though testrpc reports `invalid opcode`

**Comment by satyavh** [comment]
It happens on Ropsten as well, if I run into it I will forward you the requested info

**Comment by perissology** [comment]
I think this has been fixed
