### ISSUE TITLE
check whitelist in uploads service

### ISSUE THREAD

**Issue by perissology** [Giveth/feathers-giveth#64]
we don't use the whitelist in the uploads service, but it would probably be a good idea to do that.

reported by @mattfink on slack

**Comment by perissology** [comment]
closing, as this isn't possible. We want to allow any user to propose a milestone, thus we need to allow them to upload as well

**Comment by vojtechsimetka** [comment]
Well this will be solved by moving to IPFS, right?

**Comment by perissology** [comment]
not really. we'll need to run an ipfs node and store the data anyways
