### ISSUE TITLE
Add the unique count of people who donated to an entity

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#66]
Currently we track the amount of donations with `donationCount`. But we want to show the unique amount of people who support a project. So we need to add something like `peopleCount` to the `donationsHistory.hook.js`. This needs to count the unique givers for an entity.

**Comment by satyavh** [comment]
FYI: Counters only update on current entities after creating a new donation

**Comment by perissology** [comment]
this is fixed
