### ISSUE TITLE
allow anyone to propose a milestone

### ISSUE THREAD

**Issue by perissology** [Giveth/feathers-giveth#79]
Currently you need to be in the `projectOwnerWhitelist` to be able to propose/create a milestone.

b/c the campaign owner "accepts" proposed milestone, anyone should be able to propose them.

The challenge comes with the fact that anyone can create a milestone under a campaign directly in the contracts, thus bypassing this "propose/approve" step and potentially adding milestones to a campaign that the campaign owner never wanted.

One possible solution is that we add a milestone manager ui for the campaign owner, where the campaign owner can "accept" a milestone. The milestone can be a proposed milestone via the ui or a created milestone directly via the contracts. In the ui, we only display "accepted" milestones.

**Comment by vojtechsimetka** [comment]
I am not sure I fully understand. I thought that proposed milestones only live in UI & frathers. So it should not be possible to inject proposed milestones through contract, right?

**Comment by vojtechsimetka** [comment]
I think this is solved.
