### ISSUE TITLE
Uploads service accepts any file type of any size.

### ISSUE THREAD

**Issue by StevenJNPearce** [Giveth/feathers-giveth#98]
Problem:

Anyone could make the host OS unbootable by uploading junk to fill the disk, and possibly cause even worse damage by uploading javascript or binary files.

To Reproduce:

Create a DAC or milestone and choose whatever for the image upload.

To Fix:

uploads.service.js, mutler accepts an options object with limits and fileFilter properties, see multer docs on how to configure.

**Comment by perissology** [comment]
we run a reverse proxy in front, which limits the file size, however it is rather large lie 10mb or something.

I'll look into it. Thanks for reporting

**Comment by vojtechsimetka** [comment]
I would just like to mention, that since we are doing base64 encoding, jpegs or pngs can increase up to 3 times in size (so 3.6MB file can easily hit this limit).
